# 서론

Kotlin Coroutine의 굉장히 중요한 개념이 `cancellation`이다.

몇몇 라이브러리들은 `cancellation`개념을 도입하기 위해 함수를 suspend시킬 정도로 말이다.

<br>

그냥 Thread를 kill시키는건 connection을 닫고, resource를 free시켜야 하기 때문에 최악의 방법이다.

개발자가 계속해서 활성화 되어있는 state를 찾는 것도 불편한 방법이다.

이렇게 cancellation을 위한 좋은 방법을 계속해서 찾아가던 중, Kotlin Coroutine은 간단하고, 편하고, 안전한 방법을 찾아냈다.

# 기본 Cancellation

`Job`인터페이스는 `cancellation`을 위한 `cancel()` 메소드를 가지고 있다.

`cancel()`메소드를 호출하게 되면 다음과 같은 동작이 발생한다.

- suspend된 곳에서 작업을 끝나게 해준다.

- `Job`이 자식을 가지고 있다면 자식들도 cancel시켜준다.

  부모에게는 아무런 영향도 끼치지 않는다.

- `Job`이 cancel된 이후에는 어떠한 새로운 Coroutine의 부모 context가 될 수 없다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
       repeat(1_000) { i ->
			delay(200)
			println("Printing $i")
		}
    }
    
    delay(1100)
    job.cancel()
    job.join()
    println("Cancelled successfully")
}

Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
Cancelled successfully
```

위 에제에서 볼 수 있다싶이, 원래 200ms에 한 번씩 1000번 반복되어야 하지만,
1100ms가 지난 시점에서는 `cancel()`이 호출되기 때문에 바로 끝나는걸 확인할 수  있다.

<br>

또한, 만약 왜 cancel되었는지 이유를 설명하기 위해 Exception을 전달하고 싶을 수도 있다.

이 때 Exception은 `CancellationException`을 상속해야만 cancel할 때 사용될 수 있다.

<br>

취소 후에 취소될때까지 기다리기 위해 `join()`을 자주 사용한다.

그렇지 않으면 다음과 같이 인위적으로 부모 coroutine에서 `delay()`를 걸어줘야 한다.

```kotlin
suspend fun main() = coroutineScope {
    val job = launch {
        repeat(1_000) { i ->
			delay(100)
			Thread.sleep(100) // We simulate long operation
			println("Printing $i")
		}
    }
    
	delay(1000)
    job.cancel()
    println("Cancelled successfully")
}

Printing 0
Printing 1
Printing 2
Printing 3
Cancelled successfully
Printing 4
// 함수 종료
```

`cancel()`과 `join()`을 더 쉽게 사용하기 위해 `kotlinx.coroutines` 라이브러리는 `cancelAndJoin()`을 지원한다.

``` kotlin
public suspend fun Job.cancelAndJoin() {
    cancel()
    return join()
}
```

`Job()`이 생성된 후에 같은 방법으로 `cancel()`할 수 있다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        repeat(1_000) { i ->
			delay(200)
			println("Printing $i")
		}
    }

    delay(1100)
    job.cancelAndJoin()
    println("Cancelled successfully")
}

Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
Cancelled successfully
```

> 만약 `delay(1100)`을 지우게 되면 바로 `cancel()`되어 종료된다.

이건 굉장히 중요한 기능으로, 우리는 동시에 여러 concurrent task들을 cancel시키는 경우가 많기 때문에 편리하게 이용할 수 있다.

``` kotlin
class ProfileViewModel : ViewModel() {
    private val scope =
        CoroutineScope(Dispatchers.Main + SupervisorJob())
    
    fun onCreate() {
        scope.launch { loadUserData() }
    }
    
    override fun onCleared() {
        scope.coroutineContext.cancelChildren()
    }
// ...
}
```

# cancellation 동작 원리

Job이 cancel되었을 때, 상태를 `cancelling`으로 변경한다.

그 후 첫 번째 suspend 지점에서 `CancellationException`이 던져진다.

이 exception은 try - catch에 의해 잡아지지만, 마지막에 다시 throw 하기를 권장한다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    
    launch(job) {
        try {
            repeat(1_000) { i ->
                delay(200)
				println("Printing $i")
			}
        } catch (e: CancellationException) {
            println(e)
            throw e
        }
    }
    
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled successfully")
    delay(1000)
}

Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
JobCancellationException...
Cancelled successfully
```

cancel된 coroutine은 그냥 멈추는게 아니라 Exception을 통해 내부적으로 cancel된다는게 중요하다.

그 덕분에 우리는 `finally` 블록을 통해 db connection을 free시키는 등의 작업을 처리할 수 있다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    
    launch(job) {
        try {
            delay(Random.nextLong(2000))
            println("Done")
        } finally {
            print("Will always be printed")
        }
    }
    
    delay(1000)
    job.cancelAndJoin()
}

Will always be printed
// 또는
Done
Will always be printed

```

## `cancel()` 재호출

우리가 `CancellationException`을 catch함으로써 coroutine이 끝나기 전에 여러 처리를 할 수 있는데, 그렇다면 `cancel()`의 한계는 뭘까?

Coroutine은 resource를 free시키는걸 기다려 주는데, 이 때 suspension을 할 수 없다.

`Job`은 이미 `cancelling`상태이기 때문에 suspend되거나 새로운 coroutine을 실행시킬 수 없다.

만약 새로운 coroutine을 생성하려고 하면 무시되고, suspend하려고 하면 `CancellationException`을 던지게 된다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            delay(2000)
            println("Job is done")
        } finally {
            println("Finally")
            launch {
                // 무시된다.
                println("Will not be printed")
            }
        }
    }
    
    delay(1000) // CancellationException이 발생한다.
    
    println("Will not be printed")
    
    delay(1000)
    job.cancelAndJoin()
    println("Cancel done")
}
// (1 sec)
// Finally
// Cancel done
```

우리가 DB RollBack과 같이 정말 `cancelled`상태인 coroutine을 suspend할 일이 있을수도 있다.

그럴 때에는 해당 호출을 `withContext(NonCancellable)`로 감싸주면 된다.

> `withContext()`의 역할은 나중에 다시 자세히 설명할 것이다.

`NonCancellable`로 묶어주면 `Job`이 cancel되지 않게 막아준다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    
    launch(job) {
        try {
            delay(200)
            println("Coroutine finished")
        } finally {
            println("Finally")
            withContext(NonCancellable) { // 해당 Coroutine이 종료될 때 까지 Job이 cancel되지 않는다.
                delay(1000L)
                println("Cleanup done")
            }
        }
    }
    
    delay(100)
    job.cancelAndJoin()
    println("Done")
}
// Finally
// Cleanup done
// Done

```

## `invokeOnComplete()`

자원을 free시킬 때 사용되는 다른 방법으로는, `Job`의 `invokeOnComplete()`가 있다.

`invokeOnComplete()`는 coroutine이 **`cancelled` 상태 또는 `completed`상태일 때 실행되는 메소드**이다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        delay(1000)
    }
    
    job.invokeOnCompletion { exception: Throwable? ->
        println("Finished")
    }
    
    delay(400)
    job.cancelAndJoin()
}

Finished
```

파라미터로 넘어가는 `Throwable`은 만약 `cancelled`상태라면 `cancel`된 원인을 넘겨주게 된다.

만약 complete라면 `exception`에는 null이 들어가게 된다.

만약 `invokeOnComplete()`가 호출되기 전에 `Job`이 `completed`상태가 된다면 Handler는 해당 메소드를 즉시 실행한다.

또한, 만약 필요하다면 `onCancelling`이나 `invokeImmediately`를 파라미터로 넘겨줄 수 있다.

- **onCancelling:** true면 `cancelling`상태일 때 호출된다.
  기본값은 false이다.

- **invokeImmediately:** true면 coroutine이 이미 내가 바라는 state`(cancelling이나 completed 등)`일 때 즉시 실행된다.

  기본값은 true이다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        delay(Random.nextLong(2400))
        println("Finished")
    }
    
    delay(800)
    job.invokeOnCompletion { exception: Throwable? ->
        println("Will always be printed")
		println("The exception was: $exception")
	}

    delay(800)
    job.cancelAndJoin()
}

Will always be printed
The exception was: kotlinx.coroutines.JobCancellationException
// 만약 invokeOnCompletion이 실행되기 전에 coroutine이 completed가 된다
Finished
Will always be printed
The exception was null
```

# Stop이 불가능한 context를 stop시키기

cancellation은 suspend된 곳, 즉 `delay()`와 같은 함수가 있는 곳에서만 가능하기 때문에 **suspend될 곳이 없다면 cancel되지 않는다.**

예를 들어 `delay()`대신 `Thread.sleep()`을 사용해서 Thread를 Blocking했을수도 있다.

실제 개발 상황에서라면 복잡한 계산을 예로 들 수 있겠다.

<br>

다음 예제는 supsend 지점이 없기 때문에 coroutine이 cancel될 수 없는 상황을 나타낸다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        repeat(1_000) { i ->
			Thread.sleep(200) // 복잡한 연산이나 파일 읽기와 같은 작업이 여기 들어갈 수 있다.
			println("Printing $i")
		}
    }
    
    delay(1000)
    job.cancelAndJoin()
    println("Cancelled successfully")
    delay(1000)
}

Printing 0
Printing 1
Printing 2
//... (1000개가 모두 출력된다.)
```

## `yield()`로 suspension point 만들기

`yield()`함수는 **suspend함과 동시에 다시 resume시켜주는 메소드**이다.

suspension point를 직접 할당할 때 사용된다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        repeat(1_000) { i ->
            Thread.sleep(200)
            yield()
			println("Printing $i")
		}
    }
    
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled successfully")
    delay(1000)
}

Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
Cancelled successfully
```

## Job의 상태 추적하기

Coroutine Builder에서 `this`는 해당 builder의 scope를 의미한다.

CoroutineScope는 CoroutineContext를 property로 갖는데, 다음과 같이 사용해서 `coroutine job`을 가져올 수 있다.

``` kotlin
coroutineContext[Job]
```

`Job`을 가져온 후에는 active 여부를 가져올 수 있는데, Kotlin Coroutine 라이브러리는 다음과 같이 간단한 메소드를 지원한다.

``` kotlin
public val CoroutineScope.isActive: Boolean
	get() = coroutineContext[Job]?.isActive ?: true
```

우리는 이걸 통해서 context가 active상태가 아니면 멈출 수 있다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        do {
            Thread.sleep(200)
            println("Printing")
        } while (isActive)
    }
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled successfully")
}

Printing
Printing
Printing
Printing
Printing
Printing
Cancelled successfully
```

## `ensureActive()` 호출하기

또 다른 방법으로, `ensureActive()`메소드를 호출할 수 있다.

이 메소드는 `Job`이 active상태가 아니면 `CancellationException`을 발생시킨다.

``` kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        repeat(1000) { num ->
			Thread.sleep(200)
			ensureActive()
			println("Printing $num")
		}
    }
    
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled successfully")
}

Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
Cancelled successfully
```

`ensureActive()`와 `yield()`의 결과는 비슷해 보이지만, 전혀 다른 특징을 가지고 있다.

`ensureActive()`는 `CoroutineScope`에서 호출되어야 하고, `Job`이 active가 아니면 예외를 던질 뿐이다.

가볍기 때문에 주로 선호하는 방법이다.

<br>

반대로 `yield()`함수는 scope를 필요로 하지 않기 때문에 그냥 일반적인 suspend 함수에서도 사용할 수 있다.

`yield()`함수 자체가 suspend 직후에 resume하는 방식이기 때문에 Thread Pool과 함께 Dispatcher를 사용하면 Thread 변경이 일어날 수도 있다.

# suspendCancellableCoroutine

`suspendCoroutine`과 비슷하게 동작하는데, `suspendCancellableCoroutine`은 추가적인 메소드를 제공하는 `CancellableContinuation<T>`으로 wrapping시켜준다.

가장 중요한 것들 중 하나는 Coroutine이 cancel되었을 때 실행될 것을 정의하게 해주는 `invokeOnCancellation`이다.

이를 통해 라이브러리들이 간편하게 resource를 free할 수 있게 해준다.

``` kotlin
suspend fun someTask() = suspendCancellableCoroutine {
    cont -> cont.invokeOnCancellation {
        // do cleanup
    }
    // rest of the implementation
}
```

아래는 Retrofit에서 suspend 함수로 Wrapping한 예제다.

``` kotlin
suspend fun getOrgRepos(): List<Repo> =
	suspendCancellableCoroutine { continuation ->
		val orgReposCall = apiService.getOrgReposCall()
		orgReposCall.enqueue(object : Callback<List<Repo>> {
            override fun onResponse(
                call: Call<List<Repo>>,
                response: Response<List<Repo>>
            ) {
                if (response.isSuccessful) {
                    val body = response.body()
                    if (body != null) {
                        continuation.resume(body)
                    } else {
                        continuation.resumeWithException(ResponseWithEmptyBody)
                    }
                } else {
                    continuation.resumeWithException(
                        ApiException(
                            response.code(),
                            response.message()
                        )
                    )
                }
            }

            override fun onFailure(call: Call<List<Repo>>, t: Throwable) {
                continuation.resumeWithException(t)
            }
        })
	
        continuation.invokeOnCancellation {
            orgReposCall.cancel()
        }
	}
```

`CancellableContinuation<T>`는 추가로 `Job`의 상태를 체크하는 메소드도 지원한다.



